name: Deploy to Azure Function App (Python)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Package everything (function_app.py, host.json, app/, etc.)
      - name: Prepare artifact
        run: |
          mkdir -p build
          zip -r build/functionapp.zip . -x "*.git*"

      # Deploy using publish profile
      - name: Deploy to Azure Function App
        uses: azure/functions-action@v1
        with:
          app-name: mcf-email-svc
          package: build/functionapp.zip
          publish-profile: ${{ secrets.AZUREAPPSVC_PUBLISHPROFILE }}
